//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmlReadApp
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060001
			public const int Category = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int ListCustom = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int ListSimple = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int MainScroll = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int SimpleLayout = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int SimpleResultView = 2131099654;
			
			// aapt resource value: 0x7f060000
			public const int Title = 2131099648;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int BookItem = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ItemView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Simple = 2130903043;
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int Books = 2130968576;
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public const int ListCustom = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int ListSimple = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int SimpleSummary = 2131034112;
			
			private String()
			{
			}
		}
	}
}
